INSERT INTO UNIDADE(unidade, descricao) VALUES('Ampola', 'Ampola');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Balde', 'Balde');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Bandej', 'Bandeja');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Barra', 'Barra');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Bisnag', 'Bisnaga');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Bloco', 'Bloco');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Bobina', 'Bobina');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Bomb', 'Bombona');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Caps', 'Capsula');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cart', 'Cartela');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cento', 'Cento');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cj', 'Conjunto');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cm', 'Centimetro');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cm2', 'Centimetro Quadrado');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cx', 'Caixa');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cx2', 'Caixa com 2 Un');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cx3', 'Caixa com 3 Un');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cx5', 'Caixa com 5 Un');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cx10', 'Caixa com 10 Un');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cx15', 'Caixa com 15 Un');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cx20', 'Caixa com 20 Un');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cx25', 'Caixa com 25 Un');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cx50', 'Caixa com 50 Un');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Cx100', 'Caixa com 100 Un');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Disp', 'Display');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Duzia', 'Duzia');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Embal', 'Embalagem');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Fardo', 'Fardo');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Folha', 'Folha');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Frasco', 'Frasco');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Galao', 'Galão');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Gf', 'Garrafa');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Gramas', 'Gramas');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Jogo', 'Jogo');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Kg', 'Kg');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Kit', 'Kit');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Lata', 'Lata');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Litro', 'Litro');
INSERT INTO UNIDADE(unidade, descricao) VALUES('M', 'Metro');
INSERT INTO UNIDADE(unidade, descricao) VALUES('M2', 'Metro Quadrado');
INSERT INTO UNIDADE(unidade, descricao) VALUES('M3', 'Metro Cúbico');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Milhei', 'Milheiro');
INSERT INTO UNIDADE(unidade, descricao) VALUES('mL', 'mL');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Mwh', 'Megawatt Hora');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Pacote', 'Pacote');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Palete', 'Palete');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Pares', 'Pares');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Pc', 'Peça');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Pote', 'Pote');
INSERT INTO UNIDADE(unidade, descricao) VALUES('K', 'Quilate');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Resma', 'Resma');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Rolo', 'Rolo');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Saco', 'Saco');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Sacola', 'Sacola');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Tambor', 'Tambor');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Tanque', 'Tanque');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Ton', 'Tonelada');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Tubo', 'Tubo');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Unid', 'Unidade');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Vasil', 'Vasilhame');
INSERT INTO UNIDADE(unidade, descricao) VALUES('Vidro', 'Vidro');